apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: default
data:
  default.conf: |-
    server {
        listen 80;
        location / {
          proxy_pass http://random-dog-service/;
        }
    }