apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-dog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-dog
  template:
    metadata:
      labels:
        app: random-dog
    spec:
      containers:
      - image: logiczmaksimka/sber_devops:random_dog
        name: random-dog
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: random-dog-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: random-dog